version: "2"

linters:
  enable:
    - bodyclose
    - errorlint
    - gocritic
    - misspell
    - unconvert
  settings:
    errcheck:
      exclude-functions:
        - (*text/tabwriter.Writer).Flush
        - (*os.File).Close
  exclusions:
    presets:
      - comments
      - std-error-handling
    rules:
      - path: _test\.go
        linters: [errcheck]

formatters:
  enable:
    - gofmt
